version: "3.9"

services:
  web:
    build: .
    volumes:
      - .:/code
    ports:
      - 5000:5000
    env_file:
      - ./.env

    command: uvicorn mysite.asgi:application --reload --host 0.0.0.0 --port 5000
