# Generated by Django 4.1.4 on 2022-12-19 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                ("employee_id", models.UUIDField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100, null=True)),
                ("last_name", models.CharField(max_length=100, null=True)),
                ("phone", models.CharField(max_length=11, null=True)),
                ("image_url", models.URLField(blank=True)),
            ],
        ),
    ]
